version: '3'
services:

  djangoapp:
    build: .
    volumes:
      - .:/srv/django/fileviewer
      - ./static:/srv/django/fileviewer/static
      #- static_volume:/srv/django/fileviewer/static
      - media_volume:/srv/django/fileviewer/media
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/srv/django/fileviewer/static
      #- static_volume:/srv/django/fileviewer/static
      - media_volume:/srv/django/fileviewer/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:
  media_volume:
