# Generated by Django 2.1.5 on 2019-02-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='slug',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='Image',
        ),
    ]
